---
kind: Service
apiVersion: v1
metadata:
  name: zandronum-server
spec:
  selector:
    app: zandronum-server
  type: ClusterIP
  ports:
    - port: 10666
      protocol: TCP
      targetPort: 10666
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zandronum-server
  labels:
    app: zandronum-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zandronum-server
  template:
    metadata:
      labels:
        app: zandronum-server
    spec:
      imagePullSecrets:
        - name: docker-hub
      volumes:
      - name: zandronum-server
        persistentVolumeClaim:
          claimName: pipeline-nextcloud
      strategy:
        type: Recreate
      nodeName: rancherkube1-worker1
      containers:
        - name: send
          image: ${CICD_IMAGE}:${CICD_EXECUTION_SEQUENCE}
          args: ["coop"]
          ports:
          - containerPort: 10666
            hostPort: 10666
            name: 10666tcp106660
            protocol: UDP
          volumeMounts:
          - mountPath: /data
            name: zandronum-server
            subPath: wads
