---
kind: Service
apiVersion: v1
metadata:
  name: send
spec:
  selector:
    app: send
  type: HostPost
  ports:
    - port: 10666
      protocol: UDP
      targetPort: 10666
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zandronum-server
  labels:
    app: zandronum-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zandronum-server
  template:
    metadata:
      labels:
        app: zandronum-server
    spec:
      imagePullSecrets:
        - name: docker-hub
      containers:
        - name: send
          image: ${CICD_IMAGE}:${CICD_EXECUTION_SEQUENCE}
          ports:
          - containerPort: 10666
