version: '3.7'

services:
  coop:
    build: ../
    image: zandronum-server
    restart: always
    network_mode: host
    ports:
    - 10666:10666/udp
    volumes:
    - ./data:/data:ro
    command: coop
    environment:
      - JOIN_PASSWORD=joinpasswordhere
      - RCON_PASSWORD=rconpasswordhere
  invasion:
    build: ../
    image: zandronum-server
    restart: always
    network_mode: host
    ports:
    - 10667:10667/udp
    volumes:
    - ./data:/data:ro
    command: invasion
    environment:
      - JOIN_PASSWORD=joinpasswordhere
      - RCON_PASSWORD=rconpasswordhere
  survival:
    build: ../
    image: zandronum-server
    restart: always
    network_mode: host
    ports:
    - 10668:10668/udp
    volumes:
    - ./data:/data:ro
    command: survival
    environment:
      - JOIN_PASSWORD=joinpasswordhere
      - RCON_PASSWORD=rconpasswordhere
